/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppAchievementsRouteImport } from './routes/app.achievements'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAiCoachRouteImport } from './routes/app.ai-coach'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppGoalsRouteImport } from './routes/app.goals'
import { Route as AppJournalRouteImport } from './routes/app.journal'
import { Route as AppPortfoliosRouteImport } from './routes/app.portfolios'
import { Route as AppRiskRouteImport } from './routes/app.risk'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppTradesRouteImport } from './routes/app.trades'
import { Route as AppTradesNewRouteImport } from './routes/app.trades.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAiCoachRoute = AppAiCoachRouteImport.update({
  id: '/ai-coach',
  path: '/ai-coach',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfoliosRoute = AppPortfoliosRouteImport.update({
  id: '/portfolios',
  path: '/portfolios',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskRoute = AppRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTradesRoute = AppTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => AppRoute,
} as any)
const AppTradesNewRoute = AppTradesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppTradesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai-coach': typeof AppAiCoachRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/journal': typeof AppJournalRoute
  '/app/portfolios': typeof AppPortfoliosRoute
  '/app/risk': typeof AppRiskRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/trades': typeof AppTradesRouteWithChildren
  '/app/trades/new': typeof AppTradesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai-coach': typeof AppAiCoachRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/journal': typeof AppJournalRoute
  '/app/portfolios': typeof AppPortfoliosRoute
  '/app/risk': typeof AppRiskRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/trades': typeof AppTradesRouteWithChildren
  '/app/trades/new': typeof AppTradesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai-coach': typeof AppAiCoachRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/journal': typeof AppJournalRoute
  '/app/portfolios': typeof AppPortfoliosRoute
  '/app/risk': typeof AppRiskRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/trades': typeof AppTradesRouteWithChildren
  '/app/trades/new': typeof AppTradesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/achievements'
    | '/app/admin'
    | '/app/ai-coach'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/goals'
    | '/app/journal'
    | '/app/portfolios'
    | '/app/risk'
    | '/app/settings'
    | '/app/trades'
    | '/app/trades/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/achievements'
    | '/app/admin'
    | '/app/ai-coach'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/goals'
    | '/app/journal'
    | '/app/portfolios'
    | '/app/risk'
    | '/app/settings'
    | '/app/trades'
    | '/app/trades/new'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/achievements'
    | '/app/admin'
    | '/app/ai-coach'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/goals'
    | '/app/journal'
    | '/app/portfolios'
    | '/app/risk'
    | '/app/settings'
    | '/app/trades'
    | '/app/trades/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/achievements': {
      id: '/app/achievements'
      path: '/achievements'
      fullPath: '/app/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-coach': {
      id: '/app/ai-coach'
      path: '/ai-coach'
      fullPath: '/app/ai-coach'
      preLoaderRoute: typeof AppAiCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/goals': {
      id: '/app/goals'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/journal': {
      id: '/app/journal'
      path: '/journal'
      fullPath: '/app/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/portfolios': {
      id: '/app/portfolios'
      path: '/portfolios'
      fullPath: '/app/portfolios'
      preLoaderRoute: typeof AppPortfoliosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/risk': {
      id: '/app/risk'
      path: '/risk'
      fullPath: '/app/risk'
      preLoaderRoute: typeof AppRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trades': {
      id: '/app/trades'
      path: '/trades'
      fullPath: '/app/trades'
      preLoaderRoute: typeof AppTradesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trades/new': {
      id: '/app/trades/new'
      path: '/new'
      fullPath: '/app/trades/new'
      preLoaderRoute: typeof AppTradesNewRouteImport
      parentRoute: typeof AppTradesRoute
    }
  }
}

interface AppTradesRouteChildren {
  AppTradesNewRoute: typeof AppTradesNewRoute
}

const AppTradesRouteChildren: AppTradesRouteChildren = {
  AppTradesNewRoute: AppTradesNewRoute,
}

const AppTradesRouteWithChildren = AppTradesRoute._addFileChildren(
  AppTradesRouteChildren,
)

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppAdminRoute: typeof AppAdminRoute
  AppAiCoachRoute: typeof AppAiCoachRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppJournalRoute: typeof AppJournalRoute
  AppPortfoliosRoute: typeof AppPortfoliosRoute
  AppRiskRoute: typeof AppRiskRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTradesRoute: typeof AppTradesRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppAdminRoute: AppAdminRoute,
  AppAiCoachRoute: AppAiCoachRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppJournalRoute: AppJournalRoute,
  AppPortfoliosRoute: AppPortfoliosRoute,
  AppRiskRoute: AppRiskRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTradesRoute: AppTradesRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
